//
//  Constants.swift
//  MyBJJ
//
//  Created by Josh Bourke on 26/3/2023.
//

import Foundation

let myBJJSubmissionDescriptions = ["Triangle Choke": "The Triangle Choke is a submission technique that involves wrapping one's legs around an opponent's neck and one arm, cutting off their blood flow and causing them to submit. This versatile technique can be applied from a variety of positions and is a valuable addition to any BJJ practitioner's arsenal.",
                                   "Arm Bar": "The Arm Bar is a submission technique that involves hyperextending an opponent's elbow joint, forcing them to submit. This technique requires good control of the opponent's body and a high degree of technical skill, but can be devastatingly effective when executed properly.",
                                   "Anaconda": "The Anaconda Choke is a submission technique that involves applying pressure to an opponent's neck with the bicep and forearm, cutting off their blood flow and causing them to submit. This technique is particularly effective against larger or stronger opponents and can be executed from a variety of positions.",
                                   "Arm Triangle": "The Arm Triangle is a submission technique that involves trapping an opponent's arm against their neck and applying pressure with the bicep and forearm, cutting off their blood flow and causing them to submit. This technique is highly effective when executed properly and can be applied from a variety of positions.",
                                   "Back Triangle": "The Back Triangle is a submission technique that involves trapping an opponent in a triangle choke from a dominant back control position. By applying pressure with the legs and hips, the Back Triangle can cut off the opponent's blood flow and force them to submit. This technique requires good control of the opponent's body and a high degree of technical skill.",
                                   "Baseball Bat" : "The Baseball Bat Choke is a submission technique that involves using the gi lapel to apply pressure to an opponent's neck, cutting off their blood flow and causing them to submit. This technique is typically executed from a top position, such as mount or side control, and requires a high degree of technical skill to execute properly.",
                                   "Bulldog Choke": "The Bulldog Choke is a submission technique that involves applying pressure to an opponent's neck by using their own arm to strangle them. This technique is typically executed from a top position and requires good control of the opponent's body.",
                                   "Crucifix": "The Crucifix is a submission position that involves trapping an opponent's arms while maintaining dominant control over their body. From this position, a variety of submission techniques can be applied, including chokes and joint locks.",
                                   "D'arce": "The D'arce Choke is a submission technique that involves trapping an opponent's arm with one's own and using the other arm to apply pressure to their neck, cutting off their blood flow and causing them to submit. This technique is highly effective when executed properly and can be applied from a variety of positions.",
                                   "Ezekiel": "The Ezekiel Choke is a submission technique that involves using the sleeve of one's own gi to apply pressure to an opponent's neck, cutting off their blood flow and causing them to submit. This technique can be executed from a variety of positions and is a valuable addition to any BJJ practitioner's arsenal.",
                                   "Gogoplata": "The Gogoplata is a submission technique that involves using one's own shin to apply pressure to an opponent's neck, cutting off their blood flow and causing them to submit. This technique is highly effective when executed properly, but requires a high degree of flexibility and technical skill to perform.",
                                   "Guillotine": "The Guillotine Choke is a submission technique that involves wrapping one's arm around an opponent's neck and using the other arm to apply pressure, cutting off their blood flow and causing them to submit. This technique can be executed from a variety of positions and is a valuable addition to any BJJ practitioner's arsenal.",
                                   "Inverted Triangle": "The Inverted Triangle is a submission technique that involves wrapping one's legs around an opponent's neck and one arm in a reverse triangle configuration, cutting off their blood flow and causing them to submit. This technique requires good control of the opponent's body and a high degree of technical skill.",
                                   "North South": "The North South Choke is a submission technique that involves applying pressure to an opponent's neck by wrapping one's arm around their head and the other arm around their body, cutting off their blood flow and causing them to submit. This technique is typically executed from a top position and requires good control of the opponent's body.",
                                   "Rear Naked": "The Rear Naked Choke is a submission technique that involves wrapping one's arm around an opponent's neck and applying pressure with the bicep and forearm, cutting off their blood flow and causing them to submit. This technique is typically executed from a dominant back control position and is a highly effective submission hold.",
                                   "Von Fluke": "The Von Flue Choke is a submission technique that involves trapping an opponent's arm against their neck while in a side control position and using one's own shoulder to apply pressure to their neck, cutting off their blood flow and causing them to submit. This technique requires good control of the opponent's body and a high degree of technical skill.",
                                   "Americana": "The Americana is a submission technique that involves applying pressure to an opponent's shoulder joint, forcing them to submit. This technique is typically executed from a top position and requires good control of the opponent's body.",
                                   "Arm Crush": "Submission technique that involves applying pressure to an opponent's arm joint in a way that causes them to submit. This technique typically requires one to isolate their opponent's arm and use leverage to apply pressure to the joint in a way that causes pain or discomfort. With proper execution, the Arm Crush can be an effective technique that allows a BJJ practitioner to overcome an opponent and achieve success in competition.",
                                   "Kimura": "The Kimura is a submission technique that involves manipulating an opponent's shoulder joint, causing them to submit. This technique typically requires one to isolate their opponent's arm and use leverage to apply pressure to the joint in a way that causes pain or discomfort. With proper execution, the Kimura can be a highly effective technique that allows a BJJ practitioner to overcome an opponent and achieve success in competition.",
                                   "Wrist Lock": "The Wrist Lock is a submission technique that involves applying pressure to an opponent's wrist joint, causing them to submit. This technique typically requires one to isolate their opponent's arm and use leverage to apply pressure to the joint in a way that causes pain or discomfort. With proper execution, the Wrist Lock can be a useful technique that allows a BJJ practitioner to control their opponent and create opportunities for submissions.",
                                   "Calf slicer": "The Calf Slicer is a submission technique that involves applying pressure to an opponent's calf muscle and Achilles tendon, causing them to submit. This technique typically requires one to control their opponent's leg and use leverage to apply pressure to the targeted area in a way that causes pain or discomfort. With proper execution, the Calf Slicer can be an effective technique that allows a BJJ practitioner to overcome an opponent and achieve success in competition.",
                                   "Inside Heel Hook": "The Inside Heel Hook is a submission technique that involves manipulating an opponent's knee joint, causing them to submit. This technique typically requires one to isolate their opponent's leg and use leverage to apply pressure to the joint in a way that causes pain or discomfort. With proper execution, the Inside Heel Hook can be a highly effective technique that allows a BJJ practitioner to overcome an opponent and achieve success in competition.",
                                   "Knee Bar": "The Knee Bar is a submission technique that involves applying pressure to an opponent's knee joint, causing them to submit. This technique typically requires one to isolate their opponent's leg and use leverage to apply pressure to the joint in a way that causes pain or discomfort. With proper execution, the Knee Bar can be a valuable technique that allows a BJJ practitioner to control their opponent and create opportunities for submissions.",
                                   "Outside Heel Hook": "The Outside Heel Hook is a submission technique that involves manipulating an opponent's ankle joint, causing them to submit. This technique typically requires one to isolate their opponent's leg and use leverage to apply pressure to the joint in a way that causes pain or discomfort. With proper execution, the Outside Heel Hook can be a highly effective technique that allows a BJJ practitioner to overcome an opponent and achieve success in competition.",
                                   "Straight Leg Lock": "A submission technique that involves applying pressure to an opponent's ankle joint by flexing their foot. This technique can be executed from a variety of positions and is a valuable addition to any BJJ practitioner's arsenal. With proper execution, the Straight Foot Lock can be a highly effective technique that allows a BJJ practitioner to control their opponent and create opportunities for submissions.",
                                   "Toe Hold" : "The Toe Hold is a submission technique that involves manipulating an opponent's foot and ankle joints, causing them to submit. This technique typically requires one to isolate their opponent's leg and use leverage to apply pressure to the targeted area in a way that causes pain or discomfort. With proper execution, the Toe Hold can be a valuable technique that allows a BJJ practitioner to control their opponent and create opportunities for submissions."]
